name: CI

on:
  push:
    branches: 
      - main
    tags:
      - platform-*

jobs:
  deploy:
    name: deploy-platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo "::debug::{Deploying to production server on branch $GITHUB_REF}"
